######
# Configuration paramertes for Sphero Bolts
#####

# Limits to the speed and heading
speed_limit:   1.0
turning_limit: 3.1415

# Give an init LEDs setup
init_leds: true

# LEDs color
led_front_rgb: [1, 15, 6] # [14, 233, 94]
led_back_rgb:  [6, 1, 15] # [94, 14, 233]

# Starting LEDs matrix, expresed as a cartisian plain
# with +y pointing to the front of the robot and +x
# to the right. The color of each pixel is expresed in HEX

# Give an init matrix setup
init_matrix: false

# Complete matrix color, executed before drawing
led_matrix_rgb: [175, 175, 175]

# Drawing in LEDs matrix, expresed as a cartisian plain
# with +y pointing to the front of the robot and +x
# to the right. The color of each pixel is expresed in HEX
led_matrix_hex: ['000000','000000', '000000', '000000', '000000', '000000' ,'000000' ,'000000',
                 '000000','E95E0E', 'E95E0E', 'E95E0E', 'E95E0E', 'E95E0E' ,'000000' ,'000000',
                 '000000','000000', 'E95E0E', 'E95E0E', '000000', 'E95E0E' ,'E95E0E' ,'000000',
                 '000000','000000', 'E95E0E', 'E95E0E', '000000', '000000' ,'E95E0E' ,'000000',
                 '000000','000000', 'E95E0E', 'E95E0E', '000000', '000000' ,'E95E0E' ,'000000',
                 '000000','000000', 'E95E0E', 'E95E0E', '000000', 'E95E0E' ,'E95E0E' ,'000000',
                 '000000','E95E0E', 'E95E0E', 'E95E0E', 'E95E0E', 'E95E0E' ,'000000' ,'000000',
                 '000000','000000', '000000', '000000', '000000', '000000' ,'000000' ,'000000']